defaults:
  - _self_
  - transforms: transforms

seed: 17 #48 # 42
output_dir: "outputs/${now:%Y-%m-%d}"

data:
  dataset: edges2shoes
  num_classes: 2
  csv_path: CSV_PATH
  root_dir: ROOT_DIR
  num_workers: 16
  hr_size: 256
  augmentation: true
  paired_mode: true
  mode: translation
  class_indices: null
  normalize: true
  split: null

model_checkpoint:
  checkpoint_path: CHECKPOINT_PATH.pt
  use_ema: true
  use_lora: false

inference:
  num_inference_steps: 50
  guidance_scale: 7.5
  eta: 0.0
  inversion_schedule_name: "scaled_linear"

benchmark:
  num_samples: 32
  vis_samples: 10
  batch_size: 32

  export_intermediates: false
  export_output_dir: "results/benchmark_export/${now:%Y-%m-%d_%H-%M-%S}"
  export_save_intermediate_latents: false
  export_save_predicted_noises: false

  methods:
    - name: "standard_inversion"
      enabled: true
    
    - name: "ours"
      enabled: true
      params:
        use_cgd: true
        cgd_eta: 1000000000.0
        use_scp: true
        scp_eta: 0.0000708
        clip_frac: 1.0

    - name: "ours"
      enabled: true
      params:
        use_cgd: true
        cgd_eta: 1000000000.0
        use_scp: true
        scp_eta: 0.0000708
        clip_frac: 1.0
        forward_fraction: 0.02
    
    

metrics:
  enabled: true
  run_offline_in_benchmark: false
  live_binned: true
  n_bins: 50
  max_batches: 100
  compute_x0_mse: true
  compute_class_flip: true
  compute_cond_influence: true

logging:
  report_to: wandb
  project_name: ovg
  run_name: null